Rails.application.routes.draw do

  get 'video/new' => 'video#new', as: 'video_new'
  get 'video/show' => 'video#show'
  get 'video/index/:id' => 'video#index'
  get 'video/index' => 'video#index', as: 'video_index'
  post 'video/create' => 'video#create'
  post 'video/search' => 'video#search'
  get 'course/learn/:id' => 'course#learn'
  get 'course/index/:id' => 'course#index'
  get 'course/join_course/:id' => 'course#join_course'
  post '/course/create' => 'course#create'
  get 'course/newmanage' => 'course#newmanage'
  get 'exercise/index'
  post 'test/postavailabletest' => 'test#postAvailableTest'
  get 'test/showAnswer' => 'test#showAnswer'
  get 'test/index'
  get '/test/list/:id/' => 'test#viewtest'
  get 'test/doTest' => 'test#doTest'
  get 'test/getDoTest' => 'test#getDoTest'
  post 'test/postDoTest' => 'test#postDoTest'
  post 'test/postCustomTest' => 'test#postCustomTest'
  get 'test' => 'test#index'
  get 'course/index'
  get 'teacher/addbook' => 'teacher#addbook'
  post 'teacher/postaddbook' => 'teacher#postaddbook'
  get 'teacher/index'
  get 'grammar/index'
  get 'reading/index'
  get 'speaking/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'answers/answer'
  get 'parts/index'
  get 'books/index'
  get 'test/list' => 'test#list'
  post 'test/create' => 'test#create'
  get 'test/createTest' => 'test#createTest'
  post 'test/createTest' => 'test#createTest'
  get 'create' => 'test#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  get'register' => 'users#new'
  post'register' => 'users#create'

  get 'home' => 'main_page#home'
  get '/' => 'students#index'
  get 'students' => 'students#index'
  get 'students/:id/' => 'students#index'
  get 'books/:id/' => 'books#index'
  get '/units/:id/' => 'units#index', :as => 'units_path'
  get '/parts/:id/' => 'parts#index'
  get 'student/new/:id' => 'students#new'
  get '/answer/:id' => 'answers#answer'
  post '/answer/:id' => 'answers#answer'
  get 'adddict' => 'vocabualary#addDict'
  get '/vocabualary/:id/' => 'vocabualary#index'
  get '/speaking/:id/' => 'speaking#index'
  get '/grammar/:id/' => 'grammar#index'
  get '/reading/:id/' => 'reading#index'

  get'/teacher' => 'teacher#index'
  resources :test
  resources :students
  resources :users
  resources :teacher
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'main_page#home'
end
